version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: to-do-list
    environment:
      POSTGRES_DB: tdlDatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
