bot:
  name: ReviewFeedback
  token: 6263974772:AAESNqo1awOxUZNJsG6UnzvTQjhq9mTKKBo

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/tdlDatabase
    username: admin
    password: admin

flyway:
  url: jdbc:postgresql://localhost:5435/tdlDatabase
  user: admin
  password: admin
  enabled: true
  locations:
    - 'classpath:db/migration'
#jpa:
#  database-platform: org.hibernate.dialect.PostgreSQLDialect
#  hibernate:
#    ddl-auto: update
#  show-sql: 'true'


